# Generated by Django 5.0.3 on 2024-08-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employeeid', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='user_images/')),
            ],
        ),
    ]
