# Generated by Django 5.0.3 on 2024-08-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceMatching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='Employeeid',
        ),
        migrations.AddField(
            model_name='userdata',
            name='empid',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
